// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw3eeTG53fm_Lsr1Sqbgg9e95CCkt0VYI',
    appId: '1:1008759861991:web:project-1008759861991',
    messagingSenderId: '1008759861991',
    projectId: 'miniproject-ea4cf',
    authDomain: 'miniproject-ea4cf.firebaseapp.com',
    storageBucket: 'miniproject-ea4cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw3eeTG53fm_Lsr1Sqbgg9e95CCkt0VYI',
    appId: '1:1008759861991:android:your-android-app-id',
    messagingSenderId: '1008759861991',
    projectId: 'miniproject-ea4cf',
    storageBucket: 'miniproject-ea4cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw3eeTG53fm_Lsr1Sqbgg9e95CCkt0VYI',
    appId: '1:1008759861991:ios:your-ios-app-id',
    messagingSenderId: '1008759861991',
    projectId: 'miniproject-ea4cf',
    storageBucket: 'miniproject-ea4cf.appspot.com',
    iosBundleId: 'com.example.cyclesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw3eeTG53fm_Lsr1Sqbgg9e95CCkt0VYI',
    appId: '1:1008759861991:macos:your-macos-app-id',
    messagingSenderId: '1008759861991',
    projectId: 'miniproject-ea4cf',
    storageBucket: 'miniproject-ea4cf.appspot.com',
    iosBundleId: 'com.example.cyclesync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw3eeTG53fm_Lsr1Sqbgg9e95CCkt0VYI',
    appId: '1:1008759861991:windows:your-windows-app-id',
    messagingSenderId: '1008759861991',
    projectId: 'miniproject-ea4cf',
    storageBucket: 'miniproject-ea4cf.appspot.com',
  );
} 